# -*- coding: utf-8 -*-
"""Introducao a Data Science.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jk-WpxZPL4eO7y74ZmNsh3aTetNK_PP1
"""

import pandas as pd
notas = pd.read_csv("ratings.csv")
notas.head()

notas.shape

notas.columns = ["usuarioID", "filmeID", "nota", "momento"]
notas.head()

notas['nota'].unique()

notas['nota'].value_counts()

print("Média",notas['nota'].mean())
print("Mediana",notas['nota'].median())

notas.nota.head()

notas.nota.plot()

notas.nota.plot(kind='hist')

notas.nota.describe()

import seaborn as sns 
sns.boxplot(notas.nota)

